server:
  port: 8080

spring:
  servlet:
    # .env import
    config:
      import: optional:file:.env[.properties]

    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:
        project-id: maximal-grin-431513-j2
        bucket: trabook-20240822
  application:
    name: PLAN-MANAGER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.100.41:3306/test
    username: root
    #password:
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 34.133.241.170
    password:
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://34.64.54.36:8761//eureka


